dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ng test --coverage --coverageReporters=text-lcov >report.lcov

after_success:
  - npx coveralls <report.lcov
